name: Publish website

on:
  push:
    branches: [ source ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
      with:
        submodules: recursive
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ghp-import
    - name: Set up Ruby
      uses: ruby/setup-ruby@v1
      with:
        ruby-version: 3.0
    - name: Install taskjuggler
      run: |
        gem install taskjuggler
    - name: Publish
      run: |
        tj3 ./src/CNS.tjp -o docs/
        ghp-import -m "Generate site" -b master docs -n -p -f

